name: roots_app
description: A fantasy village-building RPG game
version: 0.1.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  intl: ^0.18.1
  cupertino_icons: ^1.0.6

  # ✅ Firebase packages - web compatible combo
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.7
  cloud_functions: ^4.7.6
  firebase_core_web: ^2.9.0

  # ✅ Needed for firebase_auth_web
  js: ^0.7.2

  vector_math: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
