name: roots_app
description: A fantasy village-building RPG game
version: 0.1.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # ✅ Firebase packages - web compatible combo
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.14.0
  firebase_core_web: ^2.9.0

  # ✅ Needed for firebase_auth_web
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
