// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKGtbJ1gUzuOdOSxRNfUmmLSFINqlOmwg',
    appId: '1:693756626112:web:e4508f00388383f3e71925',
    messagingSenderId: '693756626112',
    projectId: 'roots-backend-ce2ec',
    authDomain: 'roots-backend-ce2ec.firebaseapp.com',
    storageBucket: 'roots-backend-ce2ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo2msl_Dui6zYVH5iSbjrd6isGBR729cw',
    appId: '1:693756626112:android:d7ffa6168bf8ff8ce71925',
    messagingSenderId: '693756626112',
    projectId: 'roots-backend-ce2ec',
    storageBucket: 'roots-backend-ce2ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkBE_iqo0c7JnsnblnsiSimYx4xfuSHLQ',
    appId: '1:693756626112:ios:cacb53b16411bebbe71925',
    messagingSenderId: '693756626112',
    projectId: 'roots-backend-ce2ec',
    storageBucket: 'roots-backend-ce2ec.firebasestorage.app',
    iosBundleId: 'com.kleinhaentz.roots',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkBE_iqo0c7JnsnblnsiSimYx4xfuSHLQ',
    appId: '1:693756626112:ios:7d1ddb39b5203b39e71925',
    messagingSenderId: '693756626112',
    projectId: 'roots-backend-ce2ec',
    storageBucket: 'roots-backend-ce2ec.firebasestorage.app',
    iosBundleId: 'com.kleinhaentz.rootsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKGtbJ1gUzuOdOSxRNfUmmLSFINqlOmwg',
    appId: '1:693756626112:web:43652d9186deab1fe71925',
    messagingSenderId: '693756626112',
    projectId: 'roots-backend-ce2ec',
    authDomain: 'roots-backend-ce2ec.firebaseapp.com',
    storageBucket: 'roots-backend-ce2ec.firebasestorage.app',
  );
}
